/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.example.android.gradle.configuration

import org.gradle.testfixtures.ProjectBuilder
import kotlin.test.Test
import kotlin.test.assertNotNull

/**
 * A simple unit test for the 'com.example.android.gradle.configuration.greeting' plugin.
 */
class GradleConfigurationPluginTest {
//    @Test fun `plugin registers task`() {
//        // Create a test project and apply the plugin
//        val project = ProjectBuilder.builder().build()
//        project.plugins.apply("org.jetbrains.kotlin.android")
//        project.plugins.apply("ui-plugin")

        // Verify the result
//        assertNotNull(project.tasks.findByName("ui-plugin"))
//    }
}
